export const getReadableEntityLabel = (label: string): string => {
  const entityLabels: Record<string, string> = {
    PER: 'Person',
    PERSON: 'Person',
    ORG: 'Organization',
    ORGANIZATION: 'Organization',
    LOC: 'Location',
    LOCATION: 'Location',
    GPE: 'Location',
    DATE: 'Date',
    TIME: 'Time',
    MONEY: 'Money',
    PERCENT: 'Percentage',
    field: 'Academic Field',
    task: 'Task',
    product: 'Product',
    algorithm: 'Algorithm',
    metrics: 'Metrics',
    programlang: 'Programming Language',
    conference: 'Conference',
    book: 'Book',
    award: 'Award',
    poem: 'Poem',
    event: 'Event',
    magazine: 'Magazine',
    literarygenre: 'Literary Genre',
    discipline: 'Discipline',
    enzyme: 'Enzyme',
    protein: 'Protein',
    chemicalelement: 'Chemical Element',
    chemicalcompound: 'Chemical Compound',
    astronomicalobject: 'Astronomical Object',
    academicjournal: 'Academic Journal',
    theory: 'Theory',
  };

  return entityLabels[label] || label.charAt(0).toUpperCase() + label.slice(1);
};

export const getEntityColor = (entityType: string): string => {
  const colors: Record<string, string> = {
    PER: '#3B82F6',
    PERSON: '#3B82F6',
    ORG: '#10B981',
    ORGANIZATION: '#10B981',
    LOC: '#8B5CF6',
    LOCATION: '#8B5CF6',
    GPE: '#8B5CF6',
    DATE: '#F59E0B',
    TIME: '#F97316',
    MONEY: '#EAB308',
    PERCENT: '#EC4899',
    field: '#6366F1',
    task: '#06B6D4',
    product: '#14B8A6',
    algorithm: '#8B5CF6',
    metrics: '#F43F5E',
    programlang: '#0EA5E9',
    conference: '#84CC16',
    book: '#D946EF',
    award: '#FACC15',
    poem: '#F472B6',
    event: '#EF4444',
    magazine: '#22C55E',
    literarygenre: '#A855F7',
    discipline: '#3B82F6',
    enzyme: '#059669',
    protein: '#0D9488',
    chemicalelement: '#EA580C',
    chemicalcompound: '#D97706',
    astronomicalobject: '#4F46E5',
    academicjournal: '#0891B2',
    theory: '#7C3AED',
  };

  return colors[entityType] || '#6B7280';
};
