export const getReadableEntityLabel = (label: string): string => {
  const entityLabels: Record<string, string> = {
    PER: 'Person',
    PERSON: 'Person',
    ORG: 'Organization',
    ORGANIZATION: 'Organization',
    LOC: 'Location',
    LOCATION: 'Location',
    GPE: 'Location',
    DATE: 'Date',
    TIME: 'Time',
    MONEY: 'Money',
    PERCENT: 'Percentage',
    field: 'Academic Field',
    task: 'Task',
    product: 'Product',
    algorithm: 'Algorithm',
    metrics: 'Metrics',
    programlang: 'Programming Language',
    conference: 'Conference',
    book: 'Book',
    award: 'Award',
    poem: 'Poem',
    event: 'Event',
    magazine: 'Magazine',
    literarygenre: 'Literary Genre',
    discipline: 'Discipline',
    enzyme: 'Enzyme',
    protein: 'Protein',
    chemicalelement: 'Chemical Element',
    chemicalcompound: 'Chemical Compound',
    astronomicalobject: 'Astronomical Object',
    academicjournal: 'Academic Journal',
    theory: 'Theory',
  };

  return entityLabels[label] || label.charAt(0).toUpperCase() + label.slice(1);
};

export const getEntityColor = (entityType: string): string => {
  const colors: Record<string, string> = {
    PER: '#1E40AF',
    PERSON: '#1E40AF',
    ORG: '#047857',
    ORGANIZATION: '#047857',
    LOC: '#6D28D9',
    LOCATION: '#6D28D9',
    GPE: '#6D28D9',
    DATE: '#D97706',
    TIME: '#EA580C',
    MONEY: '#CA8A04',
    PERCENT: '#BE185D',
    field: '#4338CA',
    task: '#0891B2',
    product: '#0F766E',
    algorithm: '#6D28D9',
    metrics: '#DC2626',
    programlang: '#0369A1',
    conference: '#65A30D',
    book: '#C026D3',
    award: '#EAB308',
    poem: '#EC4899',
    event: '#DC2626',
    magazine: '#16A34A',
    literarygenre: '#9333EA',
    discipline: '#1E40AF',
    enzyme: '#047857',
    protein: '#0F766E',
    chemicalelement: '#C2410C',
    chemicalcompound: '#B45309',
    astronomicalobject: '#3730A3',
    academicjournal: '#0E7490',
    theory: '#5B21B6',
  };
  return colors[entityType] || '#374151';
};
